import React from 'react'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '@/context/authContext'
import NotesProvider from '@/context/NotesContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Core Notes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <NotesProvider>
          <body className={inter.className}>
            {children}
          </body>
        </NotesProvider>
      </AuthProvider>
    </html>
  )
}
